metadata:
- clusterType
- controlPlaneArch
- infraNodesCount
- infraNodesType
- ipsecMode
- qps
- burst
- churnCycles
- churnDelay
- churnDeletionStrategy
- churnDuration
- churnPercent
- cleanup
- iterationsPerNamespace
- jobIterations
- jobType
- maxWaitTimeout
- metricsClosing
- verifyObjects
- waitForDeletion
- waitWhenFinished
- k8sVersion
- masterNodesCount
- masterNodesType
- ocpMajorVersion
- ocpVersion
- passed
- platform
- region
- sdnType
- totalNodes
- workerArch
- workerNodesCount
- workerNodesType
job_summary_filters:
  platform.keyword: AWS
  jobConfig.name.keyword: cluster-density-v2
metrics:
  - name: podLatencyQuantilesMeasurement
    value_field: P99
    description: "The pod latency quantiles"
  - name: cpu-kube-apiserver
  - name: max-memory-sum-kube-apiserver
  - name: cpu-masters
  - name: max-memory-sum-masters
  - name: cpu-workers
  - name: max-memory-sum-workers
skip_metrics:
  churnMetric: true
  jobName.keyword: garbage-collection
  jobConfig.name.keyword: garbage-collection
discardFields: [P95, P90, P50, max, min, avg, metadata, uuid, timestamp, query, uuid]
output_prefix: output
s3_folder: cluster-density-v2
s3_bucket: kube-burner-ai-s3-bucket
chunk_size: 10000